### ISSUE TITLE
Cannot run package using Wasmer

### ISSUE THREAD

**Issue by renatoathaydes** [isurfer21/date-shortener#1]
Hi, I found your package on wapm and thought it would be fun to try it out!

I installed your package with:

```
wapm install isurfer21/date-shortener
```

Looking at your toml file, I found out that the program name is `ds`, so I ran this, as from the examples in the README page:

```
$ wapm run ds -t        
thread 'main' panicked at 'not yet implemented', /Users/abhishekkumar/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.42/src/sys.rs:102:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Error: wasm trap occured: unknown
```

Not sure if this is a bug on your package, on wasmer, or what... just thought I should let you know.. would be interested in knowing why it fails.

Cheers!

**Comment by syrusakbary** [comment]
I also came into this issue. It also happens in the WebAssembly shell:

https://webassembly.sh/?run-command=ds%20-t

```
$ ds -t
thread 'main' panicked at 'not yet implemented', /Users/abhishekkumar/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.42/src/sys.rs:102:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I think it's likely that the compiled WASI file (from Rust) doesn't yet support some syscall (current time?)
